# Generated by Django 3.1.13 on 2021-10-15 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20211015_0206'),
        ('blog', '0002_auto_20211015_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.coursecategories', verbose_name='Category'),
        ),
    ]
