# Generated by Django 3.1.13 on 2021-10-14 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmarks',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.courses'),
        ),
    ]
