# Generated by Django 3.1.13 on 2021-10-15 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211014_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='logo',
            field=models.ImageField(default='equesttechnicallms/static/img/brand/favicon.png', upload_to='courses/logo/'),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='course_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='base.coursecategories'),
        ),
    ]
